### ISSUE TITLE
async_write_some(...) fails when output callback is set and 0 bytes are sent

### ISSUE THREAD

**Issue by Halt001** [TorstenRobitzki/Sioux#23]
This isn't a biggie but when calling _boost::asio::async_write()_ with the test socket and a buffer of 0 bytes while having set an output callback this code fails:

    if ( !output_callback_.empty() )
        output_callback_( boost::asio::buffer( &output_[ output_.size() - size ], size ) );

( It is part of void socket<Iterator, Timer, Trait>::impl::undelayed_async_write_some. )

As size == 0, 

    output_[ output_.size() - size ] 

is out of bounds. 

One might of cause reason that one shouldn't call _async_write_some(...)_ with a 0 length buffer but it is always nice to not have it crash.

**Comment by TorstenRobitzki** [comment]
Thank you for pointing this out! :-) I wonder, what would be the expected behavior, when passing a zero-size buffer to `async_write()`? Looks like, that the function itself does not assert, can you do me a favor and do a quick test?

**Comment by TorstenRobitzki** [comment]
Ok, I found it: in the description of AsyncReadStream:

    If the total size of all buffers in the sequence mb is 0, the asynchronous read operation shall complete immediately and pass 0 as the argument to the handler that specifies the number of bytes read.

That means, passing 0 is well defined and asio_mocks do it wrong.

**Comment by Halt001** [comment]
I've tested it with a real socket and it indeed seems to work fine.

**Comment by TorstenRobitzki** [comment]
It's fixed now. Thank you for reporting!

**Comment by Halt001** [comment]
You may have fixed another bug than I reported. I reported sending (not reading) a buffer of 0 bytes using _**async_write_some()**_ . It appears this still fails the same way.

**Comment by TorstenRobitzki** [comment]
Ups, :-)

**Comment by TorstenRobitzki** [comment]
I tried to fix it again, unfortunately, my vector implementation doesn't check the array access and enabling STL debugging results in compile errors within boost test. Please be so kind and give me feedback, if this fixes the bug for you.

**Comment by Halt001** [comment]
Seems to work fine now, Thx. The offending code **output_[ output_.size() - size ]** doesn't seem to be reached now when size == 0.

**Comment by TorstenRobitzki** [comment]
Yep, I've implemented the same shortcut as in the read path, to simply post a call to the callback with "no error" and "no data" as arguments.
